version: '3'

services:
    nginx:
        image: nginx:alpine
        restart: always
        container_name: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./${PROJECT}:/var/www/html/
            - ./default.conf:/etc/nginx/conf.d/
        links:
            - php
    php:
        image: php:fpm
        container_name: php-fpm
        restart: always
        depends_on:
            - mariadb
        ports:
            - "9000:9000"
        volumes:
            - ./${PROJECT}:/var/www/html/
    mariadb:
        image: mariadb
        container_name : mariadb
        ports:
            - "3306:3306"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DBROOTPASSWD}
            MYSQL_DATABASE: ${PROJECT}
            MYSQL_USER: ${DBUSER}
            MYSQL_PASSWORD: ${DBPASSWD}




